// Shared design-system components (planning/10 §2). No business logic.
// Table / Dialog / form inputs are added alongside the first feature panel
// that needs them (Sprint 4+) to avoid speculative, unused code.
export { Button } from './Button'
export type { ButtonVariant } from './Button'
export { IconButton } from './IconButton'
export { Input } from './Input'
export { Badge } from './Badge'
export type { BadgeKind } from './Badge'
export { Spinner } from './Spinner'
export { EmptyState } from './EmptyState'
export { Toast } from './Toast'
export type { ToastItem } from './Toast'
export { ToastLayer } from './ToastLayer'
export { Tabs } from './Tabs'
export type { TabDef } from './Tabs'
export { Dialog } from './Dialog'
export { CopyButton } from './CopyButton'
export { Menu } from './Menu'
export type { MenuItem } from './Menu'
export { EnvironmentSwitcher } from './EnvironmentSwitcher'
export type { EnvironmentSwitcherProps } from './EnvironmentSwitcher'
export { VariableTextarea } from './VariableAutocomplete'
export type { VariableTextareaProps } from './VariableAutocomplete'
export { DYNAMIC_VARIABLE_SUGGESTIONS } from './variable-constants'
export type { VariableSuggestion } from './variable-constants'
export * from './icons'
